import type { Article, Author, Category } from './types'
/** DEV_ONLY demo newsroom data. Fictional copy and original procedural imagery; disabled for live launch. */
export const DEV_FIXTURE_MARK = 'DEV_ONLY' as const
const now = new Date()
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600_000).toISOString()
export const fixtureCategories: Category[] = [
  { id: 'cat-samachar', slug: 'samachar', nameNe: "समाचार", nameEn: "News", descriptionNe: "देशभरका सार्वजनिक सेवा, समाज र नागरिक सरोकारका समाचार।", descriptionEn: "Public-service, society and civic affairs from across Nepal." },
  { id: 'cat-rajniti', slug: 'rajniti', nameNe: "राजनीति", nameEn: "Politics", descriptionNe: "संसद, सरकार, नीति र सार्वजनिक जवाफदेहिताको कभरेज।", descriptionEn: "Parliament, government, policy and public accountability." },
  { id: 'cat-arth', slug: 'arth', nameNe: "अर्थ", nameEn: "Economy", descriptionNe: "बजार, रोजगार, उद्यम, ऊर्जा र सार्वजनिक खर्च।", descriptionEn: "Markets, jobs, enterprise, energy and public spending." },
  { id: 'cat-pradesh', slug: 'pradesh', nameNe: "प्रदेश", nameEn: "Provinces", descriptionNe: "सातै प्रदेशका स्थानीय निर्णय, पूर्वाधार र नागरिक जीवन।", descriptionEn: "Local decisions, infrastructure and civic life across all seven provinces." },
  { id: 'cat-bichar', slug: 'bichar', nameNe: "विचार", nameEn: "Opinion", descriptionNe: "समसामयिक विषयमा विश्लेषण, टिप्पणी र तर्क।", descriptionEn: "Analysis, commentary and arguments on current public issues." },
  { id: 'cat-khel', slug: 'khel', nameNe: "खेल", nameEn: "Sports", descriptionNe: "घरेलु तथा अन्तर्राष्ट्रिय खेलकुद कभरेज।", descriptionEn: "Domestic and international sports coverage." },
  { id: 'cat-bishwa', slug: 'bishwa', nameNe: "विश्व", nameEn: "World", descriptionNe: "नेपालसँग सान्दर्भिक विश्व समाचार र कूटनीतिक घटनाक्रम।", descriptionEn: "World affairs and diplomacy relevant to Nepali readers." },
  { id: 'cat-pravas', slug: 'pravas', nameNe: "प्रवास", nameEn: "Diaspora", descriptionNe: "विदेशमा रहेका नेपाली समुदाय, श्रम र अवसरका समाचार।", descriptionEn: "Nepali communities abroad, labour and opportunity." },
]

export const fixtureAuthors: Author[] = [
  { id: 'auth-1', slug: 'anusha-rai', nameNe: "अनुशा राई", nameEn: "Anusha Rai", bioNe: "राजनीति र सार्वजनिक नीति संवाददाता।", bioEn: "Politics and public-policy correspondent." },
  { id: 'auth-2', slug: 'bibek-shrestha', nameNe: "विवेक श्रेष्ठ", nameEn: "Bibek Shrestha", bioNe: "अर्थ, ऊर्जा र पूर्वाधार रिपोर्टिङ।", bioEn: "Economy, energy and infrastructure reporter." },
  { id: 'auth-3', slug: 'srijana-karki', nameNe: "सृजना कार्की", nameEn: "Srijana Karki", bioNe: "समाज र प्रदेश डेस्क।", bioEn: "Society and provinces desk." },
  { id: 'auth-4', slug: 'pratik-gurung', nameNe: "प्रतीक गुरुङ", nameEn: "Pratik Gurung", bioNe: "खेल तथा युवा मामिला संवाददाता।", bioEn: "Sports and youth affairs reporter." },
  { id: 'auth-5', slug: 'maya-thapa', nameNe: "माया थापा", nameEn: "Maya Thapa", bioNe: "प्रवास र श्रम गतिशीलता कभरेज।", bioEn: "Diaspora and labour-mobility reporter." },
  { id: 'auth-6', slug: 'nabin-acharya', nameNe: "नवीन आचार्य", nameEn: "Nabin Acharya", bioNe: "विश्व, प्रविधि र वातावरण डेस्क।", bioEn: "World, technology and environment desk." },
]

const categoryIds = Object.fromEntries(fixtureCategories.map((category) => [category.slug, category.id])) as Record<string, string>
const authorIds = fixtureAuthors.map((author) => author.id)

function demoArticle(args: { id: number; category: string; index: number; titleNe: string; titleEn: string; deckNe: string; deckEn: string; authorIndex: number; priority: number; province?: string }) : Article {
  const publishedAt = hoursAgo(args.id + Math.floor(args.id / 4))
  const isOpinion = args.category === 'bichar'
  return {
    id: `demo-${args.category}-${args.index}`, slug: `${args.category}-demo-${args.index}`, status: 'published', englishStatus: 'published',
    titleNe: args.titleNe, titleEn: args.titleEn, deckNe: args.deckNe, deckEn: args.deckEn,
    bodyNe: [
      { type: 'paragraph', text: `${args.deckNe} यो समाचार द नागरिकको विकास वातावरणका लागि तयार गरिएको काल्पनिक डेमो सामग्री हो। वास्तविक रिपोर्टिङको रूपमा प्रयोग हुँदैन।` },
      { type: 'heading2', text: isOpinion ? 'बहसको केन्द्र' : 'के हुँदैछ' },
      { type: 'paragraph', text: isOpinion ? 'यो लेखले नागरिक अनुभव, सार्वजनिक जवाफदेहिता र दीर्घकालीन प्रभावलाई केन्द्रमा राखेर तर्क अघि बढाउँछ।' : 'सम्बन्धित निकायले परीक्षण, कार्यान्वयन र सार्वजनिक जानकारीको चरणलाई क्रमशः अघि बढाउने योजना बनाएको डेमो विवरणमा उल्लेख छ।' },
      { type: 'paragraph', text: 'पूर्ण उत्पादन वातावरणमा यो स्थानमा प्रमाणित स्रोत, तथ्य, प्रतिक्रिया र सन्दर्भसहितको मौलिक समाचार रहनेछ।' },
    ],
    bodyEn: [
      { type: 'paragraph', text: `${args.deckEn} This is fictional development content created only to exercise The Nagarik interface and must not be used as real reporting.` },
      { type: 'heading2', text: isOpinion ? 'The argument' : 'What happens next' },
      { type: 'paragraph', text: isOpinion ? 'The demo essay centers citizen experience, public accountability and long-term impact.' : 'The demo scenario moves through testing, implementation and public-information stages.' },
    ],
    categoryId: categoryIds[args.category], authorIds: [authorIds[args.authorIndex]], tagSlugs: [args.category, 'demo'], province: args.province,
    hero: { id: `demo-media-${args.category}-${args.index}`, url: `/media/demo/${args.category}-${args.index}.jpg`, alt: args.titleEn, credit: 'The Nagarik · original demo visual', width: 1600, height: 900 },
    isBreaking: args.priority >= 9 && args.index === 1, editorialPriority: args.priority, attribution: 'original', corrections: [], publishedAt, updatedAt: publishedAt,
  }
}

export const fixtureArticles: Article[] = [
  demoArticle({ id: 1, category: 'samachar', index: 1, titleNe: "सार्वजनिक अस्पतालमा डिजिटल पालो प्रणालीको परीक्षण सुरु", titleEn: "Public hospitals begin testing a digital queue system", deckNe: "तीन ठूला अस्पतालमा एक महिनाको परीक्षणपछि सेवाग्राहीको प्रतीक्षा समय तुलना गरिने।", deckEn: "A one-month pilot at three major hospitals will compare patient waiting times.", authorIndex: 2, priority: 9 }),
  demoArticle({ id: 2, category: 'samachar', index: 2, titleNe: "विद्यालय बस सुरक्षाका लागि संयुक्त अनुगमन टोली परिचालन", titleEn: "Joint monitoring teams deployed for school-bus safety", deckNe: "नगर क्षेत्रका विद्यालय बसमा गति, सिट क्षमता र प्राथमिक उपचार सामग्री जाँच गरिने।", deckEn: "School buses will be checked for speed compliance, capacity and first-aid kits.", authorIndex: 0, priority: 7 }),
  demoArticle({ id: 3, category: 'samachar', index: 3, titleNe: "उपत्यकाका पाँच स्थानमा वर्षा मापन केन्द्र थपिँदै", titleEn: "Five new rainfall monitoring stations planned in the Valley", deckNe: "स्थानीय विपद् सूचना छिटो बनाउन स्वचालित सेन्सर जडानको तयारी गरिएको छ।", deckEn: "Automated sensors are planned to speed up local disaster alerts.", authorIndex: 2, priority: 6, province: 'bagmati' }),
  demoArticle({ id: 4, category: 'samachar', index: 4, titleNe: "सरकारी कार्यालयमा सेवा समय सार्वजनिक गर्ने अभियान विस्तार", titleEn: "Public offices expand service-time disclosure", deckNe: "नागरिकले कुन सेवामा कति समय लाग्छ भनेर प्रवेशद्वारमै जानकारी पाउने व्यवस्था परीक्षणमा।", deckEn: "A pilot will display expected service times at office entrances.", authorIndex: 0, priority: 5 }),
  demoArticle({ id: 5, category: 'samachar', index: 5, titleNe: "दुई नगरबीच साझा फोहोर वर्गीकरण केन्द्र सञ्चालनमा", titleEn: "Two municipalities open a shared waste-sorting centre", deckNe: "पुनःप्रयोगयोग्य सामग्री छुट्याएर ल्याण्डफिल जाने फोहोर घटाउने लक्ष्य राखिएको छ।", deckEn: "The centre aims to reduce landfill waste by separating reusable material.", authorIndex: 2, priority: 4, province: 'bagmati' }),
  demoArticle({ id: 6, category: 'rajniti', index: 1, titleNe: "संसदीय समितिले सार्वजनिक खरिद अनुगमनको नयाँ ढाँचा माग्यो", titleEn: "Parliamentary committee seeks a new public-procurement monitoring framework", deckNe: "ठूला आयोजना ढिलाइको कारण र लागत वृद्धि एउटै सार्वजनिक रिपोर्टमा राख्न प्रस्ताव।", deckEn: "The proposal would put delay causes and cost overruns in one public report.", authorIndex: 0, priority: 10 }),
  demoArticle({ id: 7, category: 'rajniti', index: 2, titleNe: "स्थानीय तहको कानुन कार्यान्वयनबारे संघीय समीक्षा बैठक", titleEn: "Federal review examines implementation of local laws", deckNe: "तीन तहबीच दोहोरिएका अधिकार र कार्यविधि स्पष्ट गर्ने विषयमा छलफल केन्द्रित।", deckEn: "The meeting focuses on clarifying overlapping powers and procedures.", authorIndex: 0, priority: 8 }),
  demoArticle({ id: 8, category: 'rajniti', index: 3, titleNe: "संसदमा नागरिक सेवा समयसीमा विधेयकमाथि सैद्धान्तिक छलफल", titleEn: "Parliament opens debate on a citizen service deadline bill", deckNe: "सेवा ढिलाइ हुँदा कारण सार्वजनिक गर्नुपर्ने प्रस्तावमाथि सांसदहरूले धारणा राखे।", deckEn: "Lawmakers debated a proposal requiring reasons when public services are delayed.", authorIndex: 0, priority: 7 }),
  demoArticle({ id: 9, category: 'rajniti', index: 4, titleNe: "दलहरूले आन्तरिक वित्तीय विवरण सार्वजनिक गर्ने साझा मापदण्डमा छलफल", titleEn: "Parties discuss a common standard for publishing internal finances", deckNe: "वार्षिक आय–व्यय विवरण एउटै ढाँचामा सार्वजनिक गर्ने प्रस्ताव अघि बढेको छ।", deckEn: "A proposal would publish annual party income and expenses in a common format.", authorIndex: 0, priority: 6 }),
  demoArticle({ id: 10, category: 'rajniti', index: 5, titleNe: "प्रदेश समन्वय परिषद्को बैठकमा कार्यान्वयन सूचकांक प्रस्ताव", titleEn: "Implementation index proposed at provincial coordination council", deckNe: "निर्णय कति कार्यान्वयन भए भन्ने त्रैमासिक सूचक सार्वजनिक गर्ने प्रस्ताव राखिएको छ।", deckEn: "A quarterly index would show how many intergovernmental decisions were implemented.", authorIndex: 2, priority: 5 }),
  demoArticle({ id: 11, category: 'arth', index: 1, titleNe: "सानो उद्यमका लागि एकद्वार दर्ता प्रणाली परीक्षणमा", titleEn: "One-stop registration pilot begins for small enterprises", deckNe: "कर, स्थानीय दर्ता र व्यवसाय अनुमति एउटै आवेदनबाट सुरु गर्ने नमुना प्रणाली तयार।", deckEn: "A pilot combines tax, local registration and business permits in one application.", authorIndex: 1, priority: 8 }),
  demoArticle({ id: 12, category: 'arth', index: 2, titleNe: "ऊर्जा बचत गर्ने उद्योगलाई ब्याज सहुलियत प्रस्ताव", titleEn: "Interest support proposed for energy-efficient industries", deckNe: "विद्युत् खपत घटाउने उपकरणमा लगानी गर्ने उद्योगलाई लक्षित कर्जा प्रस्ताव गरिएको छ।", deckEn: "Targeted lending is proposed for factories investing in energy-saving equipment.", authorIndex: 1, priority: 7 }),
  demoArticle({ id: 13, category: 'arth', index: 3, titleNe: "स्थानीय बजारमा डिजिटल मूल्यसूची अनिवार्य गर्ने तयारी", titleEn: "Digital price boards planned for municipal markets", deckNe: "दैनिक थोक र खुद्रा मूल्य सार्वजनिक गरेर मूल्य अन्तर अनुगमन गर्ने योजना।", deckEn: "The plan would publish daily wholesale and retail prices to track markups.", authorIndex: 1, priority: 6, province: 'bagmati' }),
  demoArticle({ id: 14, category: 'arth', index: 4, titleNe: "कृषि उपज ढुवानीका लागि साझा चिस्यान केन्द्रको योजना", titleEn: "Shared cold-storage hubs planned for farm produce", deckNe: "तीन उत्पादन क्षेत्र जोड्ने ढुवानी र भण्डारण मोडलमा सहकारीसँग छलफल सुरु।", deckEn: "Cooperatives are discussing a transport and storage model linking three production areas.", authorIndex: 1, priority: 5, province: 'gandaki' }),
  demoArticle({ id: 15, category: 'arth', index: 5, titleNe: "नगर ऋणपत्रबारे स्थानीय तहलाई प्राविधिक तालिम", titleEn: "Municipalities receive technical training on local bonds", deckNe: "पूर्वाधार आयोजनाका लागि दीर्घकालीन पूँजी जुटाउने प्रक्रिया र जोखिमबारे प्रशिक्षण।", deckEn: "Training covers long-term infrastructure finance processes and risks.", authorIndex: 1, priority: 4 }),
  demoArticle({ id: 16, category: 'pradesh', index: 1, titleNe: "कोशीमा नदी किनार बस्तीको जोखिम नक्सा अद्यावधिक", titleEn: "Koshi updates risk maps for riverside settlements", deckNe: "वर्षाअघि निकास मार्ग र सुरक्षित भेला स्थान पुनःचिन्हित गरिएको छ।", deckEn: "Evacuation routes and safe assembly points were remapped before the monsoon.", authorIndex: 2, priority: 8, province: 'koshi' }),
  demoArticle({ id: 17, category: 'pradesh', index: 2, titleNe: "मधेशका चार पालिकामा साझा दमकल सेवा सुरु", titleEn: "Four Madhesh municipalities launch a shared fire service", deckNe: "सीमावर्ती बजार क्षेत्रलाई लक्षित गरी संयुक्त परिचालन कक्ष स्थापना गरिएको छ।", deckEn: "A joint dispatch room will serve market areas near the border.", authorIndex: 2, priority: 7, province: 'madhesh' }),
  demoArticle({ id: 18, category: 'pradesh', index: 3, titleNe: "गण्डकीमा पदमार्ग सुरक्षा संकेत पुनःस्थापना अभियान", titleEn: "Gandaki begins replacing trail safety markers", deckNe: "मुख्य पदमार्गका पुराना दिशा संकेत र आपतकालीन सम्पर्क बोर्ड फेरिँदै।", deckEn: "Old direction signs and emergency contact boards are being replaced on major trails.", authorIndex: 2, priority: 6, province: 'gandaki' }),
  demoArticle({ id: 19, category: 'pradesh', index: 4, titleNe: "लुम्बिनीमा सिँचाइ नहरको समुदाय–आधारित अनुगमन", titleEn: "Community monitoring begins on irrigation canals in Lumbini", deckNe: "किसान समूहले पानी वितरण र मर्मत अवस्थाको मासिक विवरण सार्वजनिक गर्ने।", deckEn: "Farmer groups will publish monthly water-distribution and maintenance reports.", authorIndex: 2, priority: 5, province: 'lumbini' }),
  demoArticle({ id: 20, category: 'pradesh', index: 5, titleNe: "कर्णालीमा दुर्गम स्वास्थ्य चौकीका लागि औषधि ढुवानी तालिका", titleEn: "Karnali sets medicine-delivery schedules for remote health posts", deckNe: "मौसम बिग्रनुअघि तीन महिनाको आवश्यक औषधि भण्डारण गर्ने तयारी।", deckEn: "Remote posts will stock three months of essential medicine before severe weather.", authorIndex: 2, priority: 4, province: 'karnali' }),
  demoArticle({ id: 21, category: 'bichar', index: 1, titleNe: "सार्वजनिक सेवा सुधारमा सूचकभन्दा अनुभव किन महत्वपूर्ण छ?", titleEn: "Why citizen experience matters more than service indicators", deckNe: "सेवा छिटो भएको तथ्य मात्र होइन, नागरिकले प्रक्रिया बुझ्यो कि बुझेन भन्ने पनि मापन हुनुपर्छ।", deckEn: "Public services should measure whether citizens understand the process, not only speed.", authorIndex: 5, priority: 7 }),
  demoArticle({ id: 22, category: 'bichar', index: 2, titleNe: "शहरको विकास नक्सामा पैदल यात्रु कहाँ छन्?", titleEn: "Where are pedestrians in the urban development map?", deckNe: "सडक चौडा बनाउनु मात्र यातायात सुधार होइन; सुरक्षित हिँडाइ पनि पूर्वाधार हो।", deckEn: "Wider roads alone do not improve mobility; safe walking is infrastructure too.", authorIndex: 5, priority: 6 }),
  demoArticle({ id: 23, category: 'bichar', index: 3, titleNe: "संघीयतामा सूचना बाँडफाँटलाई प्रशासनिक काम मात्रै नमानौँ", titleEn: "Information sharing in federalism is more than administration", deckNe: "तीन तहबीच साझा तथ्यांक नहुँदा नीति बहस अनुमानमा अड्किन्छ।", deckEn: "Policy debate becomes guesswork when the three levels lack shared data.", authorIndex: 0, priority: 6 }),
  demoArticle({ id: 24, category: 'bichar', index: 4, titleNe: "खेलकुदमा प्रतिभा खोज्ने संरचना विद्यालयबाट सुरु हुनुपर्छ", titleEn: "Sports talent systems should begin in schools", deckNe: "प्रतियोगिता मात्र होइन, नियमित प्रशिक्षण र प्रशिक्षक विकासमा लगानी चाहिन्छ।", deckEn: "Investment is needed in regular coaching and coach development, not tournaments alone.", authorIndex: 3, priority: 5 }),
  demoArticle({ id: 25, category: 'bichar', index: 5, titleNe: "प्रवासी अनुभवलाई राष्ट्रिय नीति बहसमा कसरी जोड्ने?", titleEn: "How can diaspora experience enter national policy debate?", deckNe: "सीप र अनुभवको आदानप्रदानलाई औपचारिक कार्यक्रमभन्दा सजिलो नेटवर्क चाहिन्छ।", deckEn: "Skills exchange needs practical networks, not only formal programmes.", authorIndex: 4, priority: 4 }),
  demoArticle({ id: 26, category: 'khel', index: 1, titleNe: "युवा फुटबल लिगमा आठ शहरका क्लब सहभागी", titleEn: "Eight city clubs join the youth football league", deckNe: "दुई चरणमा हुने प्रतियोगितामा १९ वर्षमुनिका खेलाडीलाई प्राथमिकता।", deckEn: "The two-stage competition prioritizes under-19 players.", authorIndex: 3, priority: 8 }),
  demoArticle({ id: 27, category: 'khel', index: 2, titleNe: "महिला क्रिकेट टोलीको बन्द प्रशिक्षण सुरु", titleEn: "Women\u2019s cricket team begins closed training camp", deckNe: "फिटनेस, फिल्डिङ र लामो इनिङ खेल्ने अभ्यासमा पहिलो साता केन्द्रित।", deckEn: "The first week focuses on fitness, fielding and building longer innings.", authorIndex: 3, priority: 7 }),
  demoArticle({ id: 28, category: 'khel', index: 3, titleNe: "विद्यालय एथलेटिक्समा इलेक्ट्रोनिक टाइमिङ प्रयोग", titleEn: "Electronic timing introduced at school athletics meet", deckNe: "स्प्रिन्ट र रिले इभेन्टमा पहिलोपटक डिजिटल समय मापन प्रणाली परीक्षण।", deckEn: "Digital timing is being tested for sprint and relay events.", authorIndex: 3, priority: 6 }),
  demoArticle({ id: 29, category: 'khel', index: 4, titleNe: "पोखरामा राष्ट्रिय पौडी प्रतियोगिताका लागि नयाँ लेन मार्किङ", titleEn: "New lane markings prepared for national swimming meet in Pokhara", deckNe: "प्रतियोगिताअघि पूल मापन र सुरक्षा अभ्यास पूरा गर्ने आयोजकको योजना।", deckEn: "Organizers plan pool measurements and safety drills before the event.", authorIndex: 3, priority: 5, province: 'gandaki' }),
  demoArticle({ id: 30, category: 'khel', index: 5, titleNe: "ग्रासरुट बास्केटबल कार्यक्रम १२ जिल्लामा विस्तार", titleEn: "Grassroots basketball programme expands to 12 districts", deckNe: "स्थानीय प्रशिक्षकलाई आधारभूत कोचिङ र बाल सुरक्षा तालिम पनि दिइने।", deckEn: "Local coaches will also receive basic coaching and child-safeguarding training.", authorIndex: 3, priority: 4 }),
  demoArticle({ id: 31, category: 'bishwa', index: 1, titleNe: "हिमाली देशहरूको जलवायु अनुकूलन नेटवर्क गठनको तयारी", titleEn: "Mountain countries plan a climate-adaptation network", deckNe: "हिमनदी, पानी र पर्वतीय बस्तीको साझा डेटा प्रणालीमा प्रारम्भिक सहमति।", deckEn: "Initial agreement focuses on shared data for glaciers, water and mountain settlements.", authorIndex: 5, priority: 8 }),
  demoArticle({ id: 32, category: 'bishwa', index: 2, titleNe: "दक्षिण एसियाली शहरहरूले वायु गुणस्तर डेटा साझेदारी बढाउने", titleEn: "South Asian cities expand air-quality data sharing", deckNe: "सीमापार प्रदूषण विश्लेषणका लागि एउटै मापन ढाँचा बनाउन प्राविधिक समूह गठन।", deckEn: "A technical group will develop common measurement standards for cross-border pollution.", authorIndex: 5, priority: 7 }),
  demoArticle({ id: 33, category: 'bishwa', index: 3, titleNe: "विदेशी श्रम बजारमा सीप प्रमाणपत्र मान्यता बढाउने क्षेत्रीय छलफल", titleEn: "Regional talks examine recognition of skills certificates", deckNe: "निर्माण, हेरचाह र आतिथ्य क्षेत्रमा प्रमाणपत्र तुलना गर्ने ढाँचा प्रस्ताव।", deckEn: "A framework is proposed to compare certificates in construction, care and hospitality.", authorIndex: 4, priority: 6 }),
  demoArticle({ id: 34, category: 'bishwa', index: 4, titleNe: "डिजिटल सार्वजनिक सेवाको सुरक्षा मापदण्डमा अन्तर्राष्ट्रिय सहकार्य", titleEn: "International cooperation grows on secure digital public services", deckNe: "सरकारी पोर्टलमा न्यूनतम सुरक्षा अभ्यास र खुला प्रमाणीकरणबारे छलफल।", deckEn: "Talks cover minimum security practices and open verification for government portals.", authorIndex: 5, priority: 5 }),
  demoArticle({ id: 35, category: 'bishwa', index: 5, titleNe: "जलवायु जोखिम बीमामा साना अर्थतन्त्रका लागि नयाँ मोडलमाथि बहस", titleEn: "New climate-risk insurance models discussed for smaller economies", deckNe: "दुर्घटनापछि तत्काल पुनर्निर्माण कोष उपलब्ध गराउने क्षेत्रीय संयन्त्र प्रस्ताव।", deckEn: "A regional mechanism would provide rapid reconstruction funds after disasters.", authorIndex: 1, priority: 4 }),
  demoArticle({ id: 36, category: 'pravas', index: 1, titleNe: "विदेशी रोजगार सम्झौता नेपाली भाषामा उपलब्ध गराउने अभियान", titleEn: "Campaign pushes for Nepali-language migrant work contracts", deckNe: "प्रस्थानअघि तलब, बीमा र कामको जिम्मेवारी स्पष्ट पढ्न सकिने व्यवस्था माग।", deckEn: "The campaign seeks clearly readable pay, insurance and duty terms before departure.", authorIndex: 4, priority: 8 }),
  demoArticle({ id: 37, category: 'pravas', index: 2, titleNe: "खाडीका तीन शहरमा मोबाइल कन्सुलर सेवा शिविर", titleEn: "Mobile consular service camps planned in three Gulf cities", deckNe: "राहदानी, कागजात प्रमाणीकरण र श्रम सहायताका सेवा एकै स्थानबाट दिइने।", deckEn: "Passport, document verification and labour support will be offered at one location.", authorIndex: 4, priority: 7 }),
  demoArticle({ id: 38, category: 'pravas', index: 3, titleNe: "प्रवासी नेपाली विद्यार्थीका लागि सीप–मार्गदर्शन नेटवर्क", titleEn: "Skills mentoring network formed for Nepali students abroad", deckNe: "अध्ययनपछि काम खोज्ने चरणमा पूर्व विद्यार्थी र नयाँ विद्यार्थी जोड्ने योजना।", deckEn: "The network connects alumni with students entering the post-study job market.", authorIndex: 4, priority: 6 }),
  demoArticle({ id: 39, category: 'pravas', index: 4, titleNe: "घर फर्केका कामदारको सीप अभिलेख स्थानीय तहमा जोड्ने तयारी", titleEn: "Municipalities plan skills records for returning migrant workers", deckNe: "विदेशमा सिकेको सीपलाई स्थानीय रोजगार र उद्यम कार्यक्रमसँग जोड्ने उद्देश्य।", deckEn: "The plan links skills gained abroad to local jobs and enterprise programmes.", authorIndex: 4, priority: 5 }),
  demoArticle({ id: 40, category: 'pravas', index: 5, titleNe: "रेमिट्यान्स शुल्क तुलना गर्ने सार्वजनिक उपकरणको प्रस्ताव", titleEn: "Public remittance-fee comparison tool proposed", deckNe: "सेवा शुल्क र विनिमय दर एउटै ठाउँमा देखाएर निर्णय सजिलो बनाउने लक्ष्य।", deckEn: "The tool would show fees and exchange rates together to simplify comparison.", authorIndex: 1, priority: 4 }),
]
