import type { Article, Author, Category } from './types'

/** DEV_ONLY - never ship when LAUNCH_STATUS=live or ALLOW_DEV_FIXTURES=false */
export const DEV_FIXTURE_MARK = 'DEV_ONLY' as const

const now = new Date()
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600_000).toISOString()

export const fixtureCategories: Category[] = [
  {
    id: 'cat-samachar',
    slug: 'samachar',
    nameNe: 'समाचार',
    nameEn: 'News',
    descriptionNe: 'देशभरका ताजा र प्रमाणित समाचार।',
    descriptionEn: 'Verified national news across Nepal.',
  },
  {
    id: 'cat-rajniti',
    slug: 'rajniti',
    nameNe: 'राजनीति',
    nameEn: 'Politics',
    descriptionNe: 'संसद, सरकार र दलहरूको निर्णय।',
    descriptionEn: 'Parliament, government, and party decisions.',
  },
  {
    id: 'cat-arth',
    slug: 'arth',
    nameNe: 'अर्थ',
    nameEn: 'Economy',
    descriptionNe: 'बजार, रोजगार र सार्वजनिक खर्च।',
    descriptionEn: 'Markets, jobs, and public spending.',
  },
  {
    id: 'cat-pradesh',
    slug: 'pradesh',
    nameNe: 'प्रदेश',
    nameEn: 'Provinces',
    descriptionNe: 'सात प्रदेशका स्थानीय निर्णय र घटनाहरू।',
    descriptionEn: 'Local decisions and events from all seven provinces.',
  },
  { id: 'cat-bichar', slug: 'bichar', nameNe: 'विचार', nameEn: 'Opinion' },
  { id: 'cat-khel', slug: 'khel', nameNe: 'खेल', nameEn: 'Sports' },
  { id: 'cat-bishwa', slug: 'bishwa', nameNe: 'विश्व', nameEn: 'World' },
  { id: 'cat-pravas', slug: 'pravas', nameNe: 'प्रवास', nameEn: 'Diaspora' },
]

export const fixtureAuthors: Author[] = [
  {
    id: 'auth-1',
    slug: 'anusha-rai',
    nameNe: 'अनुशा राई',
    nameEn: 'Anusha Rai',
    bioNe: 'काठमाडौंबाट राजनीतिक रिपोर्टिङ।',
    bioEn: 'Politics desk, Kathmandu.',
  },
  {
    id: 'auth-2',
    slug: 'bibek-shrestha',
    nameNe: 'विवेक श्रेष्ठ',
    nameEn: 'Bibek Shrestha',
    bioNe: 'अर्थ र प्रदेश कभरेज।',
    bioEn: 'Economy and provinces.',
  },
]

export const fixtureArticles: Article[] = [
  {
    id: 'art-1',
    slug: 'federal-budget-debate-opens',
    status: 'published',
    englishStatus: 'published',
    titleNe: 'संघीय बजेट बहस संसदमा सुरु',
    titleEn: 'Federal budget debate opens in parliament',
    deckNe: 'विपक्षीले प्राथमिकतामाथि प्रश्न उठाए, सत्तापक्षले विकास खर्चको रक्षा गरे।',
    deckEn: 'Opposition questions priorities as the government defends development spending.',
    bodyNe: [
      {
        type: 'paragraph',
        text: 'काठमाडौं - संघीय संसदमा बजेटमाथि औपचारिक बहस सुरु भएको छ। सांसदहरूले स्वास्थ्य, शिक्षा र प्रादेशिक समानीकरण कोषमाथिको ध्यान केन्द्रित गरेका छन्।',
      },
      {
        type: 'heading2',
        text: 'प्रादेशिक आवाज',
      },
      {
        type: 'paragraph',
        text: 'सातै प्रदेशका प्रतिनिधिहरूले राजधानी केन्द्रित खर्चको आलोचना गरेका छन्। सरकारले भने ग्रामीण सडक र सिँचाइ योजनाहरू अघि बढाइने जनाएको छ।',
      },
      {
        type: 'pullQuote',
        text: 'बजेट कागजमा होइन, गाउँमा देखिनुपर्छ।',
        attribution: 'एक प्रदेश सांसद',
      },
      {
        type: 'paragraph',
        text: 'बहस यस साताभर चल्ने अपेक्षा छ। समिति चरणमा दफावार छलफल हुनेछ।',
      },
    ],
    bodyEn: [
      {
        type: 'paragraph',
        text: 'Kathmandu - Formal debate on the federal budget has opened in parliament. Lawmakers focused on health, education, and the provincial equalization fund.',
      },
      {
        type: 'heading2',
        text: 'Provincial voices',
      },
      {
        type: 'paragraph',
        text: 'Representatives from all seven provinces criticized capital-heavy spending. The government said rural roads and irrigation will move forward.',
      },
      {
        type: 'pullQuote',
        text: 'A budget must be visible in the village, not only on paper.',
        attribution: 'A provincial MP',
      },
      {
        type: 'paragraph',
        text: 'Debate is expected to run through the week before clause-by-clause committee review.',
      },
    ],
    categoryId: 'cat-rajniti',
    authorIds: ['auth-1'],
    tagSlugs: ['budget', 'parliament'],
    province: undefined,
    hero: {
      id: 'media-1',
      url: '/media/hero-budget.jpg',
      alt: 'Parliament chamber during budget session',
      credit: 'DEV_ONLY fixture',
      width: 1600,
      height: 900,
    },
    isBreaking: true,
    editorialPriority: 9,
    attribution: 'original',
    corrections: [],
    publishedAt: hoursAgo(2),
    updatedAt: hoursAgo(1),
    packageId: 'pkg-budget',
  },
  {
    id: 'art-2',
    slug: 'monsoon-preparedness-bagmati',
    status: 'published',
    englishStatus: 'draft',
    titleNe: 'बागमतीमा मनसुन पूर्वतयारी तीव्र',
    deckNe: 'जिल्ला प्रशासनले जोखिमयुक्त बस्तीमा स्थानान्तरण तयारी गरेको छ।',
    bodyNe: [
      {
        type: 'paragraph',
        text: 'हेटौंडा - बागमती प्रदेश प्रशासनले मनसुनअघि जोखिम नक्सा अद्यावधिक गरेको छ। खोला किनाराका बस्तीमा विशेष निगरानी रहनेछ।',
      },
      {
        type: 'paragraph',
        text: 'स्थानीय तहहरूलाई राहत सामग्रीको मौज्दात जाँच गर्न निर्देशन दिइएको छ।',
      },
    ],
    categoryId: 'cat-pradesh',
    authorIds: ['auth-2'],
    tagSlugs: ['monsoon', 'bagmati'],
    province: 'bagmati',
    hero: {
      id: 'media-2',
      url: '/media/province-monsoon.jpg',
      alt: 'Riverbank settlement under monsoon cloud cover',
      credit: 'DEV_ONLY fixture',
      width: 1600,
      height: 900,
    },
    isBreaking: false,
    editorialPriority: 6,
    attribution: 'original',
    corrections: [],
    publishedAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
  },
  {
    id: 'art-3',
    slug: 'remittance-costs-gulf-corridor',
    status: 'published',
    englishStatus: 'published',
    titleNe: 'खाडी करिडरमा रेमिट्यान्स खर्च घटाउने बहस',
    titleEn: 'Debate grows over remittance costs on the Gulf corridor',
    deckNe: 'प्रवासी कामदारहरूले सेवा शुल्क र विनिमय अन्तरलाई मुख्य समस्या बताएका छन्।',
    deckEn: 'Migrant workers flag fees and exchange spreads as the core problem.',
    bodyNe: [
      {
        type: 'paragraph',
        text: 'काठमाडौं - प्रवास डेस्कले खाडीबाट नेपाल आउने रकमको औसत लागत तुलना गरेको छ। केही कोरिडरमा शुल्क अझै उच्च छ।',
      },
      {
        type: 'paragraph',
        text: 'नियामकहरूले डिजिटल वालेट र बैंक साझेदारी विस्तारको कुरा गरेका छन्।',
      },
    ],
    bodyEn: [
      {
        type: 'paragraph',
        text: 'Kathmandu - The diaspora desk compared average remittance costs from the Gulf. Fees remain high on some corridors.',
      },
      {
        type: 'paragraph',
        text: 'Regulators pointed to digital wallets and bank partnerships as next steps.',
      },
    ],
    categoryId: 'cat-pravas',
    authorIds: ['auth-2', 'auth-1'],
    tagSlugs: ['remittance', 'gulf'],
    hero: {
      id: 'media-3',
      url: '/media/diaspora-remit.jpg',
      alt: 'Queue at a remittance counter',
      credit: 'DEV_ONLY fixture',
      width: 1600,
      height: 900,
    },
    isBreaking: false,
    editorialPriority: 5,
    attribution: 'original',
    corrections: [],
    publishedAt: hoursAgo(12),
    updatedAt: hoursAgo(10),
  },
  {
    id: 'art-4',
    slug: 'opinion-local-elections-turnout',
    status: 'published',
    englishStatus: 'none',
    titleNe: 'मतदान सहभागिता किन घट्दै छ?',
    deckNe: 'स्थानीय चुनावको पाठ: पहुँच मात्र पर्याप्त छैन, विश्वास चाहिन्छ।',
    bodyNe: [
      {
        type: 'paragraph',
        text: 'मतदाता थकान र युवा स्थानान्तरणले सहभागितामा असर पारेको देखिन्छ। दलहरूले ढोका-ढोका अभियानलाई डिजिटल आवाजसँग जोड्नुपर्छ।',
      },
      {
        type: 'paragraph',
        text: 'तर सहभागिता बढाउने उपाय नारा होइन, सेवाको अनुभव हो।',
      },
    ],
    categoryId: 'cat-bichar',
    authorIds: ['auth-1'],
    tagSlugs: ['elections', 'opinion'],
    isBreaking: false,
    editorialPriority: 4,
    attribution: 'original',
    corrections: [],
    publishedAt: hoursAgo(20),
    updatedAt: hoursAgo(20),
  },
  {
    id: 'art-5',
    slug: 'national-team-qualifier-win',
    status: 'published',
    englishStatus: 'published',
    titleNe: 'क्वालिफायरमा नेपाली टिमको जित',
    titleEn: 'Nepal wins qualifier match',
    deckNe: 'घरेलु मैदानमा दबाबपूर्ण खेलपछि विजय।',
    deckEn: 'A hard-fought win on home ground.',
    bodyNe: [
      { type: 'paragraph', text: 'काठमाडौं - राष्ट्रिय टिमले क्वालिफायरमा महत्वपूर्ण जित हात पारेको छ।' },
      { type: 'paragraph', text: 'अर्को चरणको तालिका शुक्रबार सार्वजनिक हुनेछ।' },
    ],
    bodyEn: [
      { type: 'paragraph', text: 'Kathmandu - The national team secured a key qualifier win.' },
      { type: 'paragraph', text: 'The next-round schedule will be published on Friday.' },
    ],
    categoryId: 'cat-khel',
    authorIds: ['auth-2'],
    tagSlugs: ['football'],
    hero: {
      id: 'media-5',
      url: '/media/sports-qualifier.jpg',
      alt: 'Football players celebrating on the pitch',
      credit: 'DEV_ONLY fixture',
      width: 1600,
      height: 900,
    },
    isBreaking: false,
    editorialPriority: 3,
    attribution: 'original',
    corrections: [],
    publishedAt: hoursAgo(8),
    updatedAt: hoursAgo(8),
  },
  {
    id: 'art-6',
    slug: 'power-trade-india-corridor',
    status: 'published',
    englishStatus: 'published',
    titleNe: 'भारतसँग विद्युत् व्यापार विस्तारको तयारी',
    titleEn: 'Nepal prepares to expand power trade with India',
    deckNe: 'वर्षायामको अतिरिक्त उत्पादन निर्यात गर्न प्रसारण क्षमता बढाइँदै।',
    deckEn: 'Transmission capacity is being raised to export monsoon surplus.',
    bodyNe: [
      { type: 'paragraph', text: 'काठमाडौं - ऊर्जा मन्त्रालयले सीमापार प्रसारण लाइनको तालिका अद्यावधिक गरेको छ।' },
      { type: 'paragraph', text: 'निजी उत्पादकहरूले भने भुक्तानी चक्र सुधारको माग गरेका छन्।' },
    ],
    bodyEn: [
      { type: 'paragraph', text: 'Kathmandu - The energy ministry updated the cross-border transmission schedule.' },
      { type: 'paragraph', text: 'Independent producers asked for clearer payment cycles.' },
    ],
    categoryId: 'cat-arth',
    authorIds: ['auth-2'],
    tagSlugs: ['energy', 'trade'],
    hero: {
      id: 'media-1',
      url: '/media/hero-budget.jpg',
      alt: 'Transmission towers against valley mist',
      credit: 'DEV_ONLY fixture',
      width: 1600,
      height: 900,
    },
    isBreaking: false,
    editorialPriority: 7,
    attribution: 'original',
    corrections: [],
    publishedAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
  },
  {
    id: 'art-7',
    slug: 'madhesh-flood-relief-audit',
    status: 'published',
    englishStatus: 'none',
    titleNe: 'मधेशमा बाढी राहत वितरणमाथि लेखापरीक्षण',
    deckNe: 'स्थानीय तहहरूले वितरण सूची सार्वजनिक गर्न थालेका छन्।',
    bodyNe: [
      { type: 'paragraph', text: 'जनकपुर - बाढी प्रभावित परिवारको राहत सूचीमा दोहोरो नाम भेटिएपछि लेखापरीक्षण सुरु भएको छ।' },
      { type: 'paragraph', text: 'प्रदेश सरकारले स्वतन्त्र अनुगमन समिति गठन गर्ने जनाएको छ।' },
    ],
    categoryId: 'cat-pradesh',
    authorIds: ['auth-2'],
    tagSlugs: ['flood', 'madhesh'],
    province: 'madhesh',
    hero: {
      id: 'media-2',
      url: '/media/province-monsoon.jpg',
      alt: 'Flooded fields in the southern plains',
      credit: 'DEV_ONLY fixture',
      width: 1600,
      height: 900,
    },
    isBreaking: false,
    editorialPriority: 6,
    attribution: 'original',
    corrections: [],
    publishedAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
  },
  {
    id: 'art-8',
    slug: 'world-climate-finance-cop',
    status: 'published',
    englishStatus: 'published',
    titleNe: 'जलवायु वित्तमा नेपालको आवाज बलियो बनाउने लक्ष्य',
    titleEn: 'Nepal aims for a stronger voice on climate finance',
    deckNe: 'हानिनोक्सानी कोषमा पहुँच सरल बनाउन कूटनीतिक तयारी।',
    deckEn: 'Diplomacy focuses on simpler access to the loss-and-damage fund.',
    bodyNe: [
      { type: 'paragraph', text: 'काठमाडौं - परराष्ट्र मन्त्रालयले जलवायु वार्ता टोलीको प्राथमिकता सार्वजनिक गरेको छ।' },
    ],
    bodyEn: [
      { type: 'paragraph', text: 'Kathmandu - The foreign ministry published priorities for the climate negotiation team.' },
    ],
    categoryId: 'cat-bishwa',
    authorIds: ['auth-1'],
    tagSlugs: ['climate'],
    hero: {
      id: 'media-3',
      url: '/media/diaspora-remit.jpg',
      alt: 'Delegates at an international climate meeting',
      credit: 'DEV_ONLY fixture',
      width: 1600,
      height: 900,
    },
    isBreaking: false,
    editorialPriority: 5,
    attribution: 'original',
    corrections: [],
    publishedAt: hoursAgo(7),
    updatedAt: hoursAgo(7),
  },
  {
    id: 'art-9',
    slug: 'samachar-airport-runway-works',
    status: 'published',
    englishStatus: 'draft',
    titleNe: 'त्रिभुवन विमानस्थल धावनमार्ग मर्मत तालिका सार्वजनिक',
    deckNe: 'रात्रिकालीन उडानमा प्रभाव कम गर्ने गरी कार्यतालिका मिलाइएको छ।',
    bodyNe: [
      { type: 'paragraph', text: 'काठमाडौं - नागरिक उड्डयन प्राधिकरणले धावनमार्ग मर्मतको समयतालिका सार्वजनिक गरेको छ।' },
      { type: 'paragraph', text: 'यात्रुहरूलाई अग्रिम जानकारी लिन आग्रह गरिएको छ।' },
    ],
    categoryId: 'cat-samachar',
    authorIds: ['auth-1'],
    tagSlugs: ['aviation'],
    hero: {
      id: 'media-5',
      url: '/media/sports-qualifier.jpg',
      alt: 'Airport runway lights at dusk',
      credit: 'DEV_ONLY fixture',
      width: 1600,
      height: 900,
    },
    isBreaking: false,
    editorialPriority: 8,
    attribution: 'original',
    corrections: [],
    publishedAt: hoursAgo(1),
    updatedAt: hoursAgo(1),
  },
  {
    id: 'art-10',
    slug: 'opinion-federalism-budget-voice',
    status: 'published',
    englishStatus: 'none',
    titleNe: 'संघीयता बजेटमा किन कमजोर सुनिन्छ?',
    deckNe: 'प्रदेशको आवाज संसदमा पुग्न संरचना मात्र होइन, समय चाहिन्छ।',
    bodyNe: [
      { type: 'paragraph', text: 'बजेट छलफलमा प्रदेशका प्राथमिकता दोहोरिन्छन् तर निर्णयमा वजन कम देखिन्छ।' },
      { type: 'pullQuote', text: 'आवाज सुन्नु र आवाज मान्नु फरक कुरा हुन्।', attribution: 'सम्पादकीय' },
    ],
    categoryId: 'cat-bichar',
    authorIds: ['auth-1'],
    tagSlugs: ['federalism', 'opinion'],
    isBreaking: false,
    editorialPriority: 7,
    attribution: 'original',
    corrections: [],
    publishedAt: hoursAgo(15),
    updatedAt: hoursAgo(15),
  },
  {
    id: 'art-11',
    slug: 'khel-women-cricket-series',
    status: 'published',
    englishStatus: 'published',
    titleNe: 'महिला क्रिकेट सिरिजको तालिका सार्वजनिक',
    titleEn: 'Women’s cricket series schedule published',
    deckNe: 'घरेलु मैदानमा तीन एकदिवसीय खेल हुने।',
    deckEn: 'Three ODIs will be played at home.',
    bodyNe: [{ type: 'paragraph', text: 'काठमाडौं - क्रिकेट संघले महिला टिमको सिरिज तालिका सार्वजनिक गरेको छ।' }],
    bodyEn: [{ type: 'paragraph', text: 'Kathmandu - The cricket association published the women’s series schedule.' }],
    categoryId: 'cat-khel',
    authorIds: ['auth-2'],
    tagSlugs: ['cricket'],
    hero: {
      id: 'media-5',
      url: '/media/sports-qualifier.jpg',
      alt: 'Cricket field under afternoon light',
      credit: 'DEV_ONLY fixture',
      width: 1600,
      height: 900,
    },
    isBreaking: false,
    editorialPriority: 4,
    attribution: 'original',
    corrections: [],
    publishedAt: hoursAgo(9),
    updatedAt: hoursAgo(9),
  },
  {
    id: 'art-12',
    slug: 'rajniti-party-meeting-coalition',
    status: 'published',
    englishStatus: 'published',
    titleNe: 'गठबन्धन बैठक: न्यूनतम साझा कार्यक्रममा छलफल',
    titleEn: 'Coalition meeting debates a minimum common program',
    deckNe: 'दलहरूले कार्यान्वयन सूची छोटो बनाउने सहमति खोजे।',
    deckEn: 'Parties sought a shorter implementation list.',
    bodyNe: [
      { type: 'paragraph', text: 'काठमाडौं - गठबन्धन दलहरूको बैठकमा साझा कार्यक्रमको प्राथमिकता छलफल भएको छ।' },
    ],
    bodyEn: [
      { type: 'paragraph', text: 'Kathmandu - Coalition parties debated priorities for a common program.' },
    ],
    categoryId: 'cat-rajniti',
    authorIds: ['auth-1'],
    tagSlugs: ['coalition'],
    hero: {
      id: 'media-1',
      url: '/media/hero-budget.jpg',
      alt: 'Party leaders arriving for a meeting',
      credit: 'DEV_ONLY fixture',
      width: 1600,
      height: 900,
    },
    isBreaking: false,
    editorialPriority: 8,
    attribution: 'original',
    corrections: [],
    publishedAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
  },
  {
    id: 'art-13',
    slug: 'budget-committee-clause-review',
    status: 'published',
    englishStatus: 'published',
    titleNe: 'बजेट समितिमा दफावार छलफल सुरु',
    titleEn: 'Clause-by-clause budget review begins in committee',
    deckNe: 'स्वास्थ्य र शिक्षा खण्डमा सांसदहरूको ध्यान केन्द्रित।',
    deckEn: 'Lawmakers focus on health and education clauses.',
    bodyNe: [
      { type: 'paragraph', text: 'काठमाडौं - संयुक्त समितिमा बजेटका दफा छलफल सुरु भएको छ।' },
      { type: 'paragraph', text: 'विपक्षीले समानुपातिक कोषको वितरण पारदर्शक बनाउन माग गरेका छन्।' },
    ],
    bodyEn: [
      { type: 'paragraph', text: 'Kathmandu - Joint committee review of budget clauses has started.' },
      { type: 'paragraph', text: 'The opposition asked for clearer equalization fund distribution.' },
    ],
    categoryId: 'cat-rajniti',
    authorIds: ['auth-1'],
    tagSlugs: ['budget', 'parliament'],
    hero: {
      id: 'media-1',
      url: '/media/hero-budget.jpg',
      alt: 'Committee room during budget review',
      credit: 'DEV_ONLY fixture',
      width: 1600,
      height: 900,
    },
    isBreaking: false,
    editorialPriority: 6,
    attribution: 'original',
    corrections: [],
    publishedAt: hoursAgo(10),
    updatedAt: hoursAgo(10),
    packageId: 'pkg-budget',
  },
]
